# -*- coding: utf-8 -*-
"""Fetal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ivy44x4uW_93TxE0isDHlFtGCxyQFGL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
!pip install scikit-posthocs
import scikit_posthocs as sp
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)
from imblearn.over_sampling import SMOTE
import shap

df = pd.read_csv("/content/fetal_health.csv")
print(df.shape)
print(df.isnull().sum())

sns.countplot(data=df,x='fetal_health')
plt.title('Fetal Health Distribution')
plt.figure(figsize=(14,10))

sns.heatmap(df.corr(),cmap='coolwarm')
plt.title('Correlation Matrix')

important_features = ['prolongued_decelerations','abnormal_short_term_variability','percentage_of_time_with_abnormal_long_term_variability']

for feature in important_features:
    plt.figure(figsize=(8,5))
    sns.boxplot( data=df, x='fetal_health', y=feature )
    plt.title(feature)

for feature in important_features:

    g1 = df[df['fetal_health']==1][feature]
    g2 = df[df['fetal_health']==2][feature]
    g3 = df[df['fetal_health']==3][feature]

    stat,p = stats.kruskal(g1,g2,g3)

    print(feature)
    print(f"Statistic={stat:.2f}")
    print(f"P-value={p:.10f}")

for feature in important_features:

    g1 = df[df['fetal_health']==1][feature]
    g2 = df[df['fetal_health']==2][feature]
    g3 = df[df['fetal_health']==3][feature]

    dunn = sp.posthoc_dunn([g1,g2,g3],p_adjust='bonferroni')
    print(f"\n===== {feature} =====")
    print(dunn)

features = [
    'percentage_of_time_with_abnormal_long_term_variability',
    'abnormal_short_term_variability',
    'prolongued_decelerations',
    'accelerations',
    'uterine_contractions',
    'baseline_value']

X = df[features]
y = df['fetal_health']
print(y.value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train,y_train)
print("Before SMOTE")
print(y_train.value_counts())

print("\nAfter SMOTE")
print(y_train_smote.value_counts())

rf_model = RandomForestClassifier(n_estimators=300,random_state=42)
rf_model.fit(X_train_smote,y_train_smote)
y_pred = rf_model.predict(X_test)

print(classification_report(y_test,y_pred))

cm = confusion_matrix(y_test,y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.show()

importance = rf_model.feature_importances_
feature_importance = pd.DataFrame({'Feature': features,'Importance': importance})
feature_importance = feature_importance.sort_values('Importance',ascending=False)
print(feature_importance)

plt.figure(figsize=(8,5))
sns.barplot(data=feature_importance,x='Importance',y='Feature')
plt.title('Random Forest Feature Importance')
plt.show()

explainer = shap.TreeExplainer(rf_model)
shap_values = explainer.shap_values(X_test)

print(type(shap_values))
print(np.array(shap_values).shape)

pathological_shap = shap_values[:, :, 2]
shap.summary_plot(
    pathological_shap,
    X_test,
    plot_type='bar'
)